# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harvard Strategic Advisors Group
email: harvardstrategicadvisorsgroup@gmail.com
description: Harvard Strategic Advisors Group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harvardstrategicadvisorsgroup.com" # the base hostname & protocol for your site
twitter_username: 

# Build settings
markdown: kramdown
